//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationInsightsExtension.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EventsFriendlyNameResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventsFriendlyNameResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplicationInsightsExtension.Resources.EventsFriendlyNameResource", typeof(EventsFriendlyNameResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Runtime Error (Event ID: 1026).
        /// </summary>
        internal static string Application__NET_Runtime_1026 {
            get {
                return ResourceManager.GetString("Application/.NET Runtime/1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Crash (Event ID: 1000).
        /// </summary>
        internal static string Application_Application_Error_1000 {
            get {
                return ResourceManager.GetString("Application/Application Error/1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target .NET framework Error (Event ID: 1310).
        /// </summary>
        internal static string Application_ASP_NET_1310 {
            get {
                return ResourceManager.GetString("Application/ASP.NET/1310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Counter Error (Event ID: 1008).
        /// </summary>
        internal static string Application_Microsoft_Windows_Perflib_1008 {
            get {
                return ResourceManager.GetString("Application/Microsoft-Windows-Perflib/1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Counter Error (Event ID: 1010).
        /// </summary>
        internal static string Application_Microsoft_Windows_Perflib_1010 {
            get {
                return ResourceManager.GetString("Application/Microsoft-Windows-Perflib/1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Counter Error (Event ID: 1023).
        /// </summary>
        internal static string Application_Microsoft_Windows_Perflib_1023 {
            get {
                return ResourceManager.GetString("Application/Microsoft-Windows-Perflib/1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Task Failure (Event ID: 1000).
        /// </summary>
        internal static string Windows_Azure_Windows_Azure_Runtime_1000 {
            get {
                return ResourceManager.GetString("Windows Azure/Windows Azure Runtime/1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Failure (Event ID: 2001).
        /// </summary>
        internal static string Windows_Azure_Windows_Azure_Runtime_2001 {
            get {
                return ResourceManager.GetString("Windows Azure/Windows Azure Runtime/2001", resourceCulture);
            }
        }
    }
}
