//Custom RegKey import
#pragma namespace ("\\\\.\\root\\cimv2\\SMS")
#pragma deleteclass("Office365ClientConfigurations2013", NOFAIL)
[SMS_Report(TRUE),SMS_Group_Name("Office365ClientConfigurations2013"),SMS_Class_ID("Office365ClientConfigurations2013|1.0")]
Class Office365ClientConfigurations2013: SMS_Class_Template
{
[SMS_Report(TRUE),key] string KeyName;
[SMS_Report(TRUE)] string InstallationPath;
[SMS_Report(TRUE)] string ClientFolder;
[SMS_Report(TRUE)] string VersionToReport;
[SMS_Report(TRUE)] string ClientCulture;
[SMS_Report(TRUE)] string CDNBaseUrl;
[SMS_Report(TRUE)] string UpdatesEnabled;
[SMS_Report(TRUE)] string AutoUpgrade;
[SMS_Report(TRUE)] string Platform;
[SMS_Report(TRUE)] string UpdateUrl;
[SMS_Report(TRUE)] string SharedComputerLicensing;
[SMS_Report(TRUE)] string UpgradeBlocked;
[SMS_Report(TRUE)] string LastScenario;
[SMS_Report(TRUE)] string LastScenarioResult;
[SMS_Report(TRUE)] string UpdatePath;
};