ConvertFrom-StringData @'
id_name_progac_off15c2r=Désinstallation de Microsoft Office
id_name_rc_status=Détection de Microsoft Office en cours...
id_name_progst_off15c2r=Cela peut prendre quelques minutes... 
'@
